### PR TITLE
Web —> master

### PR DESCRIPTION
**Pull request by marianbitsov23**
### Stable Web Version For Milestone 2
  * New Features
     * External Sign In
     * Major Design Update
     * Enhanced Registration
     * Chat page
     * Tag module
     * Logging
     * Additional Bug Fixes

### CODE REVIEW

**Review by msimov02 — APPROVED** [review]
LGTM!

**Comment by GGLozanov** [comment]
All right, that looks nice. Loving the design overhaul and new features. Great job on the milestone!

**Review by GGLozanov — APPROVED** [review]
LGTM!

**Comment by marianbitsov23** [comment]
Great job on Milestone 2.

**Pull request merged**
