### PR TITLE
Mobile-QoL-1.0 —> Mobile #2

### PR DESCRIPTION
**Pull request by GGLozanov**
The second iteration of the QoL changes for Mobile. Includes:
* Different screen size UI management, 
* Fixes for Android app icon not showing up
* Release APKs not building properly
* Image selection w/ camera bugfix
* App icon implementation for Android
* Handling of null Firestore records in Match while a user in WEB registers their info after authentication.

Requested review!

### CODE REVIEW

**Comment by GGLozanov** [comment]
Do not approve yet. There is a potentially dangerous bug when registering with an external auth provider and detaching the app (putting it in the background).

**Review by marianbitsov23 — APPROVED** [review]
LGTM!

**Comment by marianbitsov23** [comment]
Засега ipa за IOS не може да се билдне, защото доколкото знам ти трябва Apple developer account, за да билдваш и деплойваш ipa. Иначе приложението работи и за IOS, въпроса е че не можем да го realeas-нем на този етап.

**Comment by GGLozanov** [comment]
Another bug was detected wherein the main app route was popped from the non-extern register upon redirection to profile image selection. Fixed with the last commit.

**Review by msimov02 — APPROVED** [review]
LGTM!

**Comment by GGLozanov** [comment]
Changes approved.

**Pull request merged**
